using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Web;
using System.Web.Security;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.UI.WebControls.WebParts;
using System.Web.UI.HtmlControls;

public partial class UserCenter_CanlendarList : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {

        HiddenField1.Value = HttpContext.Current.User.Identity.Name;
        HiddenField2.Value = DateTime.Now.Date.ToShortDateString();
        GridView1.GridLines = Profile.GridLine;
        GridView1.AutoGenerateDeleteButton = Profile.EditSet.EnableDelete;
    }
}
