#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DataBase")]
public partial class DataBaseDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void InsertT_Apply(T_Apply instance);
  partial void UpdateT_Apply(T_Apply instance);
  partial void DeleteT_Apply(T_Apply instance);
  partial void InsertT_Assess(T_Assess instance);
  partial void UpdateT_Assess(T_Assess instance);
  partial void DeleteT_Assess(T_Assess instance);
  partial void InsertT_Bulletin(T_Bulletin instance);
  partial void UpdateT_Bulletin(T_Bulletin instance);
  partial void DeleteT_Bulletin(T_Bulletin instance);
  partial void InsertT_Calendar(T_Calendar instance);
  partial void UpdateT_Calendar(T_Calendar instance);
  partial void DeleteT_Calendar(T_Calendar instance);
  partial void InsertT_Department(T_Department instance);
  partial void UpdateT_Department(T_Department instance);
  partial void DeleteT_Department(T_Department instance);
  partial void InsertT_Laborage(T_Laborage instance);
  partial void UpdateT_Laborage(T_Laborage instance);
  partial void DeleteT_Laborage(T_Laborage instance);
  partial void InsertT_LaborageExpressions(T_LaborageExpressions instance);
  partial void UpdateT_LaborageExpressions(T_LaborageExpressions instance);
  partial void DeleteT_LaborageExpressions(T_LaborageExpressions instance);
  partial void InsertT_Message(T_Message instance);
  partial void UpdateT_Message(T_Message instance);
  partial void DeleteT_Message(T_Message instance);
  partial void InsertT_SmtpInfo(T_SmtpInfo instance);
  partial void UpdateT_SmtpInfo(T_SmtpInfo instance);
  partial void DeleteT_SmtpInfo(T_SmtpInfo instance);
  partial void InsertT_Training(T_Training instance);
  partial void UpdateT_Training(T_Training instance);
  partial void DeleteT_Training(T_Training instance);
  partial void InsertT_WorkHourst(T_WorkHourst instance);
  partial void UpdateT_WorkHourst(T_WorkHourst instance);
  partial void DeleteT_WorkHourst(T_WorkHourst instance);
  partial void InsertT_WorkingTime(T_WorkingTime instance);
  partial void UpdateT_WorkingTime(T_WorkingTime instance);
  partial void DeleteT_WorkingTime(T_WorkingTime instance);
  #endregion
	
	public DataBaseDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DataBaseConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataBaseDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataBaseDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataBaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataBaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<T_Apply> T_Apply
	{
		get
		{
			return this.GetTable<T_Apply>();
		}
	}
	
	public System.Data.Linq.Table<T_Assess> T_Assess
	{
		get
		{
			return this.GetTable<T_Assess>();
		}
	}
	
	public System.Data.Linq.Table<T_Bulletin> T_Bulletin
	{
		get
		{
			return this.GetTable<T_Bulletin>();
		}
	}
	
	public System.Data.Linq.Table<T_Calendar> T_Calendar
	{
		get
		{
			return this.GetTable<T_Calendar>();
		}
	}
	
	public System.Data.Linq.Table<T_Department> T_Department
	{
		get
		{
			return this.GetTable<T_Department>();
		}
	}
	
	public System.Data.Linq.Table<T_Laborage> T_Laborage
	{
		get
		{
			return this.GetTable<T_Laborage>();
		}
	}
	
	public System.Data.Linq.Table<T_LaborageExpressions> T_LaborageExpressions
	{
		get
		{
			return this.GetTable<T_LaborageExpressions>();
		}
	}
	
	public System.Data.Linq.Table<T_Message> T_Message
	{
		get
		{
			return this.GetTable<T_Message>();
		}
	}
	
	public System.Data.Linq.Table<T_SmtpInfo> T_SmtpInfo
	{
		get
		{
			return this.GetTable<T_SmtpInfo>();
		}
	}
	
	public System.Data.Linq.Table<T_Training> T_Training
	{
		get
		{
			return this.GetTable<T_Training>();
		}
	}
	
	public System.Data.Linq.Table<T_WorkHourst> T_WorkHourst
	{
		get
		{
			return this.GetTable<T_WorkHourst>();
		}
	}
	
	public System.Data.Linq.Table<T_WorkingTime> T_WorkingTime
	{
		get
		{
			return this.GetTable<T_WorkingTime>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Apply")]
public partial class T_Apply : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Apl_ID;
	
	private System.Nullable<int> _Dpt_ID;
	
	private string _Apl_work;
	
	private int _Apl_Amount;
	
	private string _Apl_qualification;
	
	private System.Nullable<bool> _Apl_Status;
	
	private string _Apl_Note;
	
	private EntityRef<T_Department> _T_Department;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnApl_IDChanging(int value);
    partial void OnApl_IDChanged();
    partial void OnDpt_IDChanging(System.Nullable<int> value);
    partial void OnDpt_IDChanged();
    partial void OnApl_workChanging(string value);
    partial void OnApl_workChanged();
    partial void OnApl_AmountChanging(int value);
    partial void OnApl_AmountChanged();
    partial void OnApl_qualificationChanging(string value);
    partial void OnApl_qualificationChanged();
    partial void OnApl_StatusChanging(System.Nullable<bool> value);
    partial void OnApl_StatusChanged();
    partial void OnApl_NoteChanging(string value);
    partial void OnApl_NoteChanged();
    #endregion
	
	public T_Apply()
	{
		this._T_Department = default(EntityRef<T_Department>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apl_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Apl_ID
	{
		get
		{
			return this._Apl_ID;
		}
		set
		{
			if ((this._Apl_ID != value))
			{
				this.OnApl_IDChanging(value);
				this.SendPropertyChanging();
				this._Apl_ID = value;
				this.SendPropertyChanged("Apl_ID");
				this.OnApl_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dpt_ID", DbType="Int")]
	public System.Nullable<int> Dpt_ID
	{
		get
		{
			return this._Dpt_ID;
		}
		set
		{
			if ((this._Dpt_ID != value))
			{
				if (this._T_Department.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnDpt_IDChanging(value);
				this.SendPropertyChanging();
				this._Dpt_ID = value;
				this.SendPropertyChanged("Dpt_ID");
				this.OnDpt_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apl_work", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string Apl_work
	{
		get
		{
			return this._Apl_work;
		}
		set
		{
			if ((this._Apl_work != value))
			{
				this.OnApl_workChanging(value);
				this.SendPropertyChanging();
				this._Apl_work = value;
				this.SendPropertyChanged("Apl_work");
				this.OnApl_workChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apl_Amount", DbType="Int NOT NULL")]
	public int Apl_Amount
	{
		get
		{
			return this._Apl_Amount;
		}
		set
		{
			if ((this._Apl_Amount != value))
			{
				this.OnApl_AmountChanging(value);
				this.SendPropertyChanging();
				this._Apl_Amount = value;
				this.SendPropertyChanged("Apl_Amount");
				this.OnApl_AmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apl_qualification", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
	public string Apl_qualification
	{
		get
		{
			return this._Apl_qualification;
		}
		set
		{
			if ((this._Apl_qualification != value))
			{
				this.OnApl_qualificationChanging(value);
				this.SendPropertyChanging();
				this._Apl_qualification = value;
				this.SendPropertyChanged("Apl_qualification");
				this.OnApl_qualificationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apl_Status", DbType="Bit")]
	public System.Nullable<bool> Apl_Status
	{
		get
		{
			return this._Apl_Status;
		}
		set
		{
			if ((this._Apl_Status != value))
			{
				this.OnApl_StatusChanging(value);
				this.SendPropertyChanging();
				this._Apl_Status = value;
				this.SendPropertyChanged("Apl_Status");
				this.OnApl_StatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apl_Note", DbType="NVarChar(100)")]
	public string Apl_Note
	{
		get
		{
			return this._Apl_Note;
		}
		set
		{
			if ((this._Apl_Note != value))
			{
				this.OnApl_NoteChanging(value);
				this.SendPropertyChanging();
				this._Apl_Note = value;
				this.SendPropertyChanged("Apl_Note");
				this.OnApl_NoteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="T_Department_T_Apply", Storage="_T_Department", ThisKey="Dpt_ID", OtherKey="Dpt_ID", IsForeignKey=true)]
	public T_Department T_Department
	{
		get
		{
			return this._T_Department.Entity;
		}
		set
		{
			T_Department previousValue = this._T_Department.Entity;
			if (((previousValue != value) 
						|| (this._T_Department.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._T_Department.Entity = null;
					previousValue.T_Apply.Remove(this);
				}
				this._T_Department.Entity = value;
				if ((value != null))
				{
					value.T_Apply.Add(this);
					this._Dpt_ID = value.Dpt_ID;
				}
				else
				{
					this._Dpt_ID = default(Nullable<int>);
				}
				this.SendPropertyChanged("T_Department");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Assess")]
public partial class T_Assess : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Ass_ID;
	
	private string _EmployeeName;
	
	private string _Ass_Data;
	
	private System.DateTime _Ass_Date;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAss_IDChanging(int value);
    partial void OnAss_IDChanged();
    partial void OnEmployeeNameChanging(string value);
    partial void OnEmployeeNameChanged();
    partial void OnAss_DataChanging(string value);
    partial void OnAss_DataChanged();
    partial void OnAss_DateChanging(System.DateTime value);
    partial void OnAss_DateChanged();
    #endregion
	
	public T_Assess()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ass_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Ass_ID
	{
		get
		{
			return this._Ass_ID;
		}
		set
		{
			if ((this._Ass_ID != value))
			{
				this.OnAss_IDChanging(value);
				this.SendPropertyChanging();
				this._Ass_ID = value;
				this.SendPropertyChanged("Ass_ID");
				this.OnAss_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string EmployeeName
	{
		get
		{
			return this._EmployeeName;
		}
		set
		{
			if ((this._EmployeeName != value))
			{
				this.OnEmployeeNameChanging(value);
				this.SendPropertyChanging();
				this._EmployeeName = value;
				this.SendPropertyChanged("EmployeeName");
				this.OnEmployeeNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ass_Data", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Ass_Data
	{
		get
		{
			return this._Ass_Data;
		}
		set
		{
			if ((this._Ass_Data != value))
			{
				this.OnAss_DataChanging(value);
				this.SendPropertyChanging();
				this._Ass_Data = value;
				this.SendPropertyChanged("Ass_Data");
				this.OnAss_DataChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ass_Date", DbType="DateTime NOT NULL")]
	public System.DateTime Ass_Date
	{
		get
		{
			return this._Ass_Date;
		}
		set
		{
			if ((this._Ass_Date != value))
			{
				this.OnAss_DateChanging(value);
				this.SendPropertyChanging();
				this._Ass_Date = value;
				this.SendPropertyChanged("Ass_Date");
				this.OnAss_DateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Bulletin")]
public partial class T_Bulletin : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _B_ID;
	
	private string _B_Content;
	
	private System.DateTime _B_Time;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnB_IDChanging(int value);
    partial void OnB_IDChanged();
    partial void OnB_ContentChanging(string value);
    partial void OnB_ContentChanged();
    partial void OnB_TimeChanging(System.DateTime value);
    partial void OnB_TimeChanged();
    #endregion
	
	public T_Bulletin()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int B_ID
	{
		get
		{
			return this._B_ID;
		}
		set
		{
			if ((this._B_ID != value))
			{
				this.OnB_IDChanging(value);
				this.SendPropertyChanging();
				this._B_ID = value;
				this.SendPropertyChanged("B_ID");
				this.OnB_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B_Content", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string B_Content
	{
		get
		{
			return this._B_Content;
		}
		set
		{
			if ((this._B_Content != value))
			{
				this.OnB_ContentChanging(value);
				this.SendPropertyChanging();
				this._B_Content = value;
				this.SendPropertyChanged("B_Content");
				this.OnB_ContentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B_Time", DbType="DateTime NOT NULL")]
	public System.DateTime B_Time
	{
		get
		{
			return this._B_Time;
		}
		set
		{
			if ((this._B_Time != value))
			{
				this.OnB_TimeChanging(value);
				this.SendPropertyChanging();
				this._B_Time = value;
				this.SendPropertyChanged("B_Time");
				this.OnB_TimeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Calendar")]
public partial class T_Calendar : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private decimal _Cld_ID;
	
	private string _EmployeeName;
	
	private string _Cld_Title;
	
	private string _Cld_Content;
	
	private System.DateTime _Cld_Date;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCld_IDChanging(decimal value);
    partial void OnCld_IDChanged();
    partial void OnEmployeeNameChanging(string value);
    partial void OnEmployeeNameChanged();
    partial void OnCld_TitleChanging(string value);
    partial void OnCld_TitleChanged();
    partial void OnCld_ContentChanging(string value);
    partial void OnCld_ContentChanged();
    partial void OnCld_DateChanging(System.DateTime value);
    partial void OnCld_DateChanged();
    #endregion
	
	public T_Calendar()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cld_ID", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public decimal Cld_ID
	{
		get
		{
			return this._Cld_ID;
		}
		set
		{
			if ((this._Cld_ID != value))
			{
				this.OnCld_IDChanging(value);
				this.SendPropertyChanging();
				this._Cld_ID = value;
				this.SendPropertyChanged("Cld_ID");
				this.OnCld_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string EmployeeName
	{
		get
		{
			return this._EmployeeName;
		}
		set
		{
			if ((this._EmployeeName != value))
			{
				this.OnEmployeeNameChanging(value);
				this.SendPropertyChanging();
				this._EmployeeName = value;
				this.SendPropertyChanged("EmployeeName");
				this.OnEmployeeNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cld_Title", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string Cld_Title
	{
		get
		{
			return this._Cld_Title;
		}
		set
		{
			if ((this._Cld_Title != value))
			{
				this.OnCld_TitleChanging(value);
				this.SendPropertyChanging();
				this._Cld_Title = value;
				this.SendPropertyChanged("Cld_Title");
				this.OnCld_TitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cld_Content", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string Cld_Content
	{
		get
		{
			return this._Cld_Content;
		}
		set
		{
			if ((this._Cld_Content != value))
			{
				this.OnCld_ContentChanging(value);
				this.SendPropertyChanging();
				this._Cld_Content = value;
				this.SendPropertyChanged("Cld_Content");
				this.OnCld_ContentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cld_Date", DbType="DateTime NOT NULL")]
	public System.DateTime Cld_Date
	{
		get
		{
			return this._Cld_Date;
		}
		set
		{
			if ((this._Cld_Date != value))
			{
				this.OnCld_DateChanging(value);
				this.SendPropertyChanging();
				this._Cld_Date = value;
				this.SendPropertyChanged("Cld_Date");
				this.OnCld_DateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Department")]
public partial class T_Department : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Dpt_ID;
	
	private string _Dpt_Name;
	
	private EntitySet<T_Apply> _T_Apply;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDpt_IDChanging(int value);
    partial void OnDpt_IDChanged();
    partial void OnDpt_NameChanging(string value);
    partial void OnDpt_NameChanged();
    #endregion
	
	public T_Department()
	{
		this._T_Apply = new EntitySet<T_Apply>(new Action<T_Apply>(this.attach_T_Apply), new Action<T_Apply>(this.detach_T_Apply));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dpt_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Dpt_ID
	{
		get
		{
			return this._Dpt_ID;
		}
		set
		{
			if ((this._Dpt_ID != value))
			{
				this.OnDpt_IDChanging(value);
				this.SendPropertyChanging();
				this._Dpt_ID = value;
				this.SendPropertyChanged("Dpt_ID");
				this.OnDpt_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dpt_Name", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string Dpt_Name
	{
		get
		{
			return this._Dpt_Name;
		}
		set
		{
			if ((this._Dpt_Name != value))
			{
				this.OnDpt_NameChanging(value);
				this.SendPropertyChanging();
				this._Dpt_Name = value;
				this.SendPropertyChanged("Dpt_Name");
				this.OnDpt_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="T_Department_T_Apply", Storage="_T_Apply", ThisKey="Dpt_ID", OtherKey="Dpt_ID")]
	public EntitySet<T_Apply> T_Apply
	{
		get
		{
			return this._T_Apply;
		}
		set
		{
			this._T_Apply.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_T_Apply(T_Apply entity)
	{
		this.SendPropertyChanging();
		entity.T_Department = this;
	}
	
	private void detach_T_Apply(T_Apply entity)
	{
		this.SendPropertyChanging();
		entity.T_Department = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Laborage")]
public partial class T_Laborage : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Lbg_ID;
	
	private string _Lbg_Year;
	
	private string _Lbg_Month;
	
	private System.Nullable<decimal> _Lbg_EndLaborage;
	
	private string _EmployeeName;
	
	private System.Nullable<decimal> _Lbg_Sastion;
	
	private System.Nullable<decimal> _Lbg_ss_Bus;
	
	private System.Nullable<decimal> _Lbg_ss_Meal;
	
	private System.Nullable<double> _Lbg_ss_Cess;
	
	private System.Nullable<decimal> _Lbg_inspire;
	
	private System.Nullable<decimal> _Lbg_Punish;
	
	private string _Lbg_Text;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLbg_IDChanging(int value);
    partial void OnLbg_IDChanged();
    partial void OnLbg_YearChanging(string value);
    partial void OnLbg_YearChanged();
    partial void OnLbg_MonthChanging(string value);
    partial void OnLbg_MonthChanged();
    partial void OnLbg_EndLaborageChanging(System.Nullable<decimal> value);
    partial void OnLbg_EndLaborageChanged();
    partial void OnEmployeeNameChanging(string value);
    partial void OnEmployeeNameChanged();
    partial void OnLbg_SastionChanging(System.Nullable<decimal> value);
    partial void OnLbg_SastionChanged();
    partial void OnLbg_ss_BusChanging(System.Nullable<decimal> value);
    partial void OnLbg_ss_BusChanged();
    partial void OnLbg_ss_MealChanging(System.Nullable<decimal> value);
    partial void OnLbg_ss_MealChanged();
    partial void OnLbg_ss_CessChanging(System.Nullable<double> value);
    partial void OnLbg_ss_CessChanged();
    partial void OnLbg_inspireChanging(System.Nullable<decimal> value);
    partial void OnLbg_inspireChanged();
    partial void OnLbg_PunishChanging(System.Nullable<decimal> value);
    partial void OnLbg_PunishChanged();
    partial void OnLbg_TextChanging(string value);
    partial void OnLbg_TextChanged();
    #endregion
	
	public T_Laborage()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lbg_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Lbg_ID
	{
		get
		{
			return this._Lbg_ID;
		}
		set
		{
			if ((this._Lbg_ID != value))
			{
				this.OnLbg_IDChanging(value);
				this.SendPropertyChanging();
				this._Lbg_ID = value;
				this.SendPropertyChanged("Lbg_ID");
				this.OnLbg_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lbg_Year", DbType="NVarChar(4) NOT NULL", CanBeNull=false)]
	public string Lbg_Year
	{
		get
		{
			return this._Lbg_Year;
		}
		set
		{
			if ((this._Lbg_Year != value))
			{
				this.OnLbg_YearChanging(value);
				this.SendPropertyChanging();
				this._Lbg_Year = value;
				this.SendPropertyChanged("Lbg_Year");
				this.OnLbg_YearChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lbg_Month", DbType="NVarChar(2) NOT NULL", CanBeNull=false)]
	public string Lbg_Month
	{
		get
		{
			return this._Lbg_Month;
		}
		set
		{
			if ((this._Lbg_Month != value))
			{
				this.OnLbg_MonthChanging(value);
				this.SendPropertyChanging();
				this._Lbg_Month = value;
				this.SendPropertyChanged("Lbg_Month");
				this.OnLbg_MonthChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lbg_EndLaborage", DbType="Money")]
	public System.Nullable<decimal> Lbg_EndLaborage
	{
		get
		{
			return this._Lbg_EndLaborage;
		}
		set
		{
			if ((this._Lbg_EndLaborage != value))
			{
				this.OnLbg_EndLaborageChanging(value);
				this.SendPropertyChanging();
				this._Lbg_EndLaborage = value;
				this.SendPropertyChanged("Lbg_EndLaborage");
				this.OnLbg_EndLaborageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string EmployeeName
	{
		get
		{
			return this._EmployeeName;
		}
		set
		{
			if ((this._EmployeeName != value))
			{
				this.OnEmployeeNameChanging(value);
				this.SendPropertyChanging();
				this._EmployeeName = value;
				this.SendPropertyChanged("EmployeeName");
				this.OnEmployeeNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lbg_Sastion", DbType="Money")]
	public System.Nullable<decimal> Lbg_Sastion
	{
		get
		{
			return this._Lbg_Sastion;
		}
		set
		{
			if ((this._Lbg_Sastion != value))
			{
				this.OnLbg_SastionChanging(value);
				this.SendPropertyChanging();
				this._Lbg_Sastion = value;
				this.SendPropertyChanged("Lbg_Sastion");
				this.OnLbg_SastionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lbg_ss_Bus", DbType="Money")]
	public System.Nullable<decimal> Lbg_ss_Bus
	{
		get
		{
			return this._Lbg_ss_Bus;
		}
		set
		{
			if ((this._Lbg_ss_Bus != value))
			{
				this.OnLbg_ss_BusChanging(value);
				this.SendPropertyChanging();
				this._Lbg_ss_Bus = value;
				this.SendPropertyChanged("Lbg_ss_Bus");
				this.OnLbg_ss_BusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lbg_ss_Meal", DbType="Money")]
	public System.Nullable<decimal> Lbg_ss_Meal
	{
		get
		{
			return this._Lbg_ss_Meal;
		}
		set
		{
			if ((this._Lbg_ss_Meal != value))
			{
				this.OnLbg_ss_MealChanging(value);
				this.SendPropertyChanging();
				this._Lbg_ss_Meal = value;
				this.SendPropertyChanged("Lbg_ss_Meal");
				this.OnLbg_ss_MealChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lbg_ss_Cess", DbType="Float")]
	public System.Nullable<double> Lbg_ss_Cess
	{
		get
		{
			return this._Lbg_ss_Cess;
		}
		set
		{
			if ((this._Lbg_ss_Cess != value))
			{
				this.OnLbg_ss_CessChanging(value);
				this.SendPropertyChanging();
				this._Lbg_ss_Cess = value;
				this.SendPropertyChanged("Lbg_ss_Cess");
				this.OnLbg_ss_CessChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lbg_inspire", DbType="Money")]
	public System.Nullable<decimal> Lbg_inspire
	{
		get
		{
			return this._Lbg_inspire;
		}
		set
		{
			if ((this._Lbg_inspire != value))
			{
				this.OnLbg_inspireChanging(value);
				this.SendPropertyChanging();
				this._Lbg_inspire = value;
				this.SendPropertyChanged("Lbg_inspire");
				this.OnLbg_inspireChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lbg_Punish", DbType="Money")]
	public System.Nullable<decimal> Lbg_Punish
	{
		get
		{
			return this._Lbg_Punish;
		}
		set
		{
			if ((this._Lbg_Punish != value))
			{
				this.OnLbg_PunishChanging(value);
				this.SendPropertyChanging();
				this._Lbg_Punish = value;
				this.SendPropertyChanged("Lbg_Punish");
				this.OnLbg_PunishChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lbg_Text", DbType="NVarChar(100)")]
	public string Lbg_Text
	{
		get
		{
			return this._Lbg_Text;
		}
		set
		{
			if ((this._Lbg_Text != value))
			{
				this.OnLbg_TextChanging(value);
				this.SendPropertyChanging();
				this._Lbg_Text = value;
				this.SendPropertyChanged("Lbg_Text");
				this.OnLbg_TextChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_LaborageExpressions")]
public partial class T_LaborageExpressions : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _LE_ID;
	
	private string _Expressions;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLE_IDChanging(int value);
    partial void OnLE_IDChanged();
    partial void OnExpressionsChanging(string value);
    partial void OnExpressionsChanged();
    #endregion
	
	public T_LaborageExpressions()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LE_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int LE_ID
	{
		get
		{
			return this._LE_ID;
		}
		set
		{
			if ((this._LE_ID != value))
			{
				this.OnLE_IDChanging(value);
				this.SendPropertyChanging();
				this._LE_ID = value;
				this.SendPropertyChanged("LE_ID");
				this.OnLE_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expressions", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Expressions
	{
		get
		{
			return this._Expressions;
		}
		set
		{
			if ((this._Expressions != value))
			{
				this.OnExpressionsChanging(value);
				this.SendPropertyChanging();
				this._Expressions = value;
				this.SendPropertyChanged("Expressions");
				this.OnExpressionsChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Message")]
public partial class T_Message : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Msg_ID;
	
	private string _Msg_Receive;
	
	private string _Msg_Send;
	
	private string _Msg_Title;
	
	private string _Msg_Content;
	
	private System.Nullable<bool> _Msg_Status;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMsg_IDChanging(int value);
    partial void OnMsg_IDChanged();
    partial void OnMsg_ReceiveChanging(string value);
    partial void OnMsg_ReceiveChanged();
    partial void OnMsg_SendChanging(string value);
    partial void OnMsg_SendChanged();
    partial void OnMsg_TitleChanging(string value);
    partial void OnMsg_TitleChanged();
    partial void OnMsg_ContentChanging(string value);
    partial void OnMsg_ContentChanged();
    partial void OnMsg_StatusChanging(System.Nullable<bool> value);
    partial void OnMsg_StatusChanged();
    #endregion
	
	public T_Message()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Msg_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Msg_ID
	{
		get
		{
			return this._Msg_ID;
		}
		set
		{
			if ((this._Msg_ID != value))
			{
				this.OnMsg_IDChanging(value);
				this.SendPropertyChanging();
				this._Msg_ID = value;
				this.SendPropertyChanged("Msg_ID");
				this.OnMsg_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Msg_Receive", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string Msg_Receive
	{
		get
		{
			return this._Msg_Receive;
		}
		set
		{
			if ((this._Msg_Receive != value))
			{
				this.OnMsg_ReceiveChanging(value);
				this.SendPropertyChanging();
				this._Msg_Receive = value;
				this.SendPropertyChanged("Msg_Receive");
				this.OnMsg_ReceiveChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Msg_Send", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string Msg_Send
	{
		get
		{
			return this._Msg_Send;
		}
		set
		{
			if ((this._Msg_Send != value))
			{
				this.OnMsg_SendChanging(value);
				this.SendPropertyChanging();
				this._Msg_Send = value;
				this.SendPropertyChanged("Msg_Send");
				this.OnMsg_SendChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Msg_Title", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string Msg_Title
	{
		get
		{
			return this._Msg_Title;
		}
		set
		{
			if ((this._Msg_Title != value))
			{
				this.OnMsg_TitleChanging(value);
				this.SendPropertyChanging();
				this._Msg_Title = value;
				this.SendPropertyChanged("Msg_Title");
				this.OnMsg_TitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Msg_Content", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string Msg_Content
	{
		get
		{
			return this._Msg_Content;
		}
		set
		{
			if ((this._Msg_Content != value))
			{
				this.OnMsg_ContentChanging(value);
				this.SendPropertyChanging();
				this._Msg_Content = value;
				this.SendPropertyChanged("Msg_Content");
				this.OnMsg_ContentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Msg_Status", DbType="Bit")]
	public System.Nullable<bool> Msg_Status
	{
		get
		{
			return this._Msg_Status;
		}
		set
		{
			if ((this._Msg_Status != value))
			{
				this.OnMsg_StatusChanging(value);
				this.SendPropertyChanging();
				this._Msg_Status = value;
				this.SendPropertyChanged("Msg_Status");
				this.OnMsg_StatusChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_SmtpInfo")]
public partial class T_SmtpInfo : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _S_ID;
	
	private string _S_Host;
	
	private int _S_Port;
	
	private string _S_UserName;
	
	private string _S_Mail;
	
	private string _S_Password;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnS_IDChanging(int value);
    partial void OnS_IDChanged();
    partial void OnS_HostChanging(string value);
    partial void OnS_HostChanged();
    partial void OnS_PortChanging(int value);
    partial void OnS_PortChanged();
    partial void OnS_UserNameChanging(string value);
    partial void OnS_UserNameChanged();
    partial void OnS_MailChanging(string value);
    partial void OnS_MailChanged();
    partial void OnS_PasswordChanging(string value);
    partial void OnS_PasswordChanged();
    #endregion
	
	public T_SmtpInfo()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int S_ID
	{
		get
		{
			return this._S_ID;
		}
		set
		{
			if ((this._S_ID != value))
			{
				this.OnS_IDChanging(value);
				this.SendPropertyChanging();
				this._S_ID = value;
				this.SendPropertyChanged("S_ID");
				this.OnS_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Host", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string S_Host
	{
		get
		{
			return this._S_Host;
		}
		set
		{
			if ((this._S_Host != value))
			{
				this.OnS_HostChanging(value);
				this.SendPropertyChanging();
				this._S_Host = value;
				this.SendPropertyChanged("S_Host");
				this.OnS_HostChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Port", DbType="Int NOT NULL")]
	public int S_Port
	{
		get
		{
			return this._S_Port;
		}
		set
		{
			if ((this._S_Port != value))
			{
				this.OnS_PortChanging(value);
				this.SendPropertyChanging();
				this._S_Port = value;
				this.SendPropertyChanged("S_Port");
				this.OnS_PortChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_UserName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string S_UserName
	{
		get
		{
			return this._S_UserName;
		}
		set
		{
			if ((this._S_UserName != value))
			{
				this.OnS_UserNameChanging(value);
				this.SendPropertyChanging();
				this._S_UserName = value;
				this.SendPropertyChanged("S_UserName");
				this.OnS_UserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Mail", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string S_Mail
	{
		get
		{
			return this._S_Mail;
		}
		set
		{
			if ((this._S_Mail != value))
			{
				this.OnS_MailChanging(value);
				this.SendPropertyChanging();
				this._S_Mail = value;
				this.SendPropertyChanged("S_Mail");
				this.OnS_MailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string S_Password
	{
		get
		{
			return this._S_Password;
		}
		set
		{
			if ((this._S_Password != value))
			{
				this.OnS_PasswordChanging(value);
				this.SendPropertyChanging();
				this._S_Password = value;
				this.SendPropertyChanged("S_Password");
				this.OnS_PasswordChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_Training")]
public partial class T_Training : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Trn_ID;
	
	private string _Trn_Title;
	
	private string _Trn_Text;
	
	private System.DateTime _Trn_Date;
	
	private string _Trn_People;
	
	private string _Trn_Note;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTrn_IDChanging(int value);
    partial void OnTrn_IDChanged();
    partial void OnTrn_TitleChanging(string value);
    partial void OnTrn_TitleChanged();
    partial void OnTrn_TextChanging(string value);
    partial void OnTrn_TextChanged();
    partial void OnTrn_DateChanging(System.DateTime value);
    partial void OnTrn_DateChanged();
    partial void OnTrn_PeopleChanging(string value);
    partial void OnTrn_PeopleChanged();
    partial void OnTrn_NoteChanging(string value);
    partial void OnTrn_NoteChanged();
    #endregion
	
	public T_Training()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trn_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Trn_ID
	{
		get
		{
			return this._Trn_ID;
		}
		set
		{
			if ((this._Trn_ID != value))
			{
				this.OnTrn_IDChanging(value);
				this.SendPropertyChanging();
				this._Trn_ID = value;
				this.SendPropertyChanged("Trn_ID");
				this.OnTrn_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trn_Title", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string Trn_Title
	{
		get
		{
			return this._Trn_Title;
		}
		set
		{
			if ((this._Trn_Title != value))
			{
				this.OnTrn_TitleChanging(value);
				this.SendPropertyChanging();
				this._Trn_Title = value;
				this.SendPropertyChanged("Trn_Title");
				this.OnTrn_TitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trn_Text", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
	public string Trn_Text
	{
		get
		{
			return this._Trn_Text;
		}
		set
		{
			if ((this._Trn_Text != value))
			{
				this.OnTrn_TextChanging(value);
				this.SendPropertyChanging();
				this._Trn_Text = value;
				this.SendPropertyChanged("Trn_Text");
				this.OnTrn_TextChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trn_Date", DbType="DateTime NOT NULL")]
	public System.DateTime Trn_Date
	{
		get
		{
			return this._Trn_Date;
		}
		set
		{
			if ((this._Trn_Date != value))
			{
				this.OnTrn_DateChanging(value);
				this.SendPropertyChanging();
				this._Trn_Date = value;
				this.SendPropertyChanged("Trn_Date");
				this.OnTrn_DateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trn_People", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string Trn_People
	{
		get
		{
			return this._Trn_People;
		}
		set
		{
			if ((this._Trn_People != value))
			{
				this.OnTrn_PeopleChanging(value);
				this.SendPropertyChanging();
				this._Trn_People = value;
				this.SendPropertyChanged("Trn_People");
				this.OnTrn_PeopleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trn_Note", DbType="NVarChar(100)")]
	public string Trn_Note
	{
		get
		{
			return this._Trn_Note;
		}
		set
		{
			if ((this._Trn_Note != value))
			{
				this.OnTrn_NoteChanging(value);
				this.SendPropertyChanging();
				this._Trn_Note = value;
				this.SendPropertyChanged("Trn_Note");
				this.OnTrn_NoteChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_WorkHourst")]
public partial class T_WorkHourst : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _WH_ID;
	
	private string _WH_StartTime;
	
	private string _WH_EndTime;
	
	private string _WH_Text;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWH_IDChanging(int value);
    partial void OnWH_IDChanged();
    partial void OnWH_StartTimeChanging(string value);
    partial void OnWH_StartTimeChanged();
    partial void OnWH_EndTimeChanging(string value);
    partial void OnWH_EndTimeChanged();
    partial void OnWH_TextChanging(string value);
    partial void OnWH_TextChanged();
    #endregion
	
	public T_WorkHourst()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WH_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int WH_ID
	{
		get
		{
			return this._WH_ID;
		}
		set
		{
			if ((this._WH_ID != value))
			{
				this.OnWH_IDChanging(value);
				this.SendPropertyChanging();
				this._WH_ID = value;
				this.SendPropertyChanged("WH_ID");
				this.OnWH_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WH_StartTime", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
	public string WH_StartTime
	{
		get
		{
			return this._WH_StartTime;
		}
		set
		{
			if ((this._WH_StartTime != value))
			{
				this.OnWH_StartTimeChanging(value);
				this.SendPropertyChanging();
				this._WH_StartTime = value;
				this.SendPropertyChanged("WH_StartTime");
				this.OnWH_StartTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WH_EndTime", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
	public string WH_EndTime
	{
		get
		{
			return this._WH_EndTime;
		}
		set
		{
			if ((this._WH_EndTime != value))
			{
				this.OnWH_EndTimeChanging(value);
				this.SendPropertyChanging();
				this._WH_EndTime = value;
				this.SendPropertyChanged("WH_EndTime");
				this.OnWH_EndTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WH_Text", DbType="NVarChar(50)")]
	public string WH_Text
	{
		get
		{
			return this._WH_Text;
		}
		set
		{
			if ((this._WH_Text != value))
			{
				this.OnWH_TextChanging(value);
				this.SendPropertyChanging();
				this._WH_Text = value;
				this.SendPropertyChanged("WH_Text");
				this.OnWH_TextChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.T_WorkingTime")]
public partial class T_WorkingTime : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _WT_ID;
	
	private string _EmployeeName;
	
	private string _WT_OnWorking;
	
	private string _WT_OffWorking;
	
	private System.DateTime _WT_Date;
	
	private string _WT_Text;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWT_IDChanging(int value);
    partial void OnWT_IDChanged();
    partial void OnEmployeeNameChanging(string value);
    partial void OnEmployeeNameChanged();
    partial void OnWT_OnWorkingChanging(string value);
    partial void OnWT_OnWorkingChanged();
    partial void OnWT_OffWorkingChanging(string value);
    partial void OnWT_OffWorkingChanged();
    partial void OnWT_DateChanging(System.DateTime value);
    partial void OnWT_DateChanged();
    partial void OnWT_TextChanging(string value);
    partial void OnWT_TextChanged();
    #endregion
	
	public T_WorkingTime()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WT_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int WT_ID
	{
		get
		{
			return this._WT_ID;
		}
		set
		{
			if ((this._WT_ID != value))
			{
				this.OnWT_IDChanging(value);
				this.SendPropertyChanging();
				this._WT_ID = value;
				this.SendPropertyChanged("WT_ID");
				this.OnWT_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string EmployeeName
	{
		get
		{
			return this._EmployeeName;
		}
		set
		{
			if ((this._EmployeeName != value))
			{
				this.OnEmployeeNameChanging(value);
				this.SendPropertyChanging();
				this._EmployeeName = value;
				this.SendPropertyChanged("EmployeeName");
				this.OnEmployeeNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WT_OnWorking", DbType="NVarChar(5)")]
	public string WT_OnWorking
	{
		get
		{
			return this._WT_OnWorking;
		}
		set
		{
			if ((this._WT_OnWorking != value))
			{
				this.OnWT_OnWorkingChanging(value);
				this.SendPropertyChanging();
				this._WT_OnWorking = value;
				this.SendPropertyChanged("WT_OnWorking");
				this.OnWT_OnWorkingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WT_OffWorking", DbType="NVarChar(5)")]
	public string WT_OffWorking
	{
		get
		{
			return this._WT_OffWorking;
		}
		set
		{
			if ((this._WT_OffWorking != value))
			{
				this.OnWT_OffWorkingChanging(value);
				this.SendPropertyChanging();
				this._WT_OffWorking = value;
				this.SendPropertyChanged("WT_OffWorking");
				this.OnWT_OffWorkingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WT_Date", DbType="DateTime NOT NULL")]
	public System.DateTime WT_Date
	{
		get
		{
			return this._WT_Date;
		}
		set
		{
			if ((this._WT_Date != value))
			{
				this.OnWT_DateChanging(value);
				this.SendPropertyChanging();
				this._WT_Date = value;
				this.SendPropertyChanged("WT_Date");
				this.OnWT_DateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WT_Text", DbType="NVarChar(50)")]
	public string WT_Text
	{
		get
		{
			return this._WT_Text;
		}
		set
		{
			if ((this._WT_Text != value))
			{
				this.OnWT_TextChanging(value);
				this.SendPropertyChanging();
				this._WT_Text = value;
				this.SendPropertyChanged("WT_Text");
				this.OnWT_TextChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
